export enum CustomPostHogEvents {
  Scrubbing = "scrubbing",
  Pause = "pause",
  Play = "play",
  EnableCaptions = "enable_captions",
  DisableCaptions = "disable_captions",
  AirPlayStarted = "airplay_started",
  AirPlayStopped = "airplay_stopped",
  ChromecastStarted = "chromecast_started",
  ChromecastStopped = "chromecast_stopped",
  ResolutionChanged = "resolution_changed",
  MuteAudio = "mute_audio",
  UnmuteAudio = "unmute_audio",
  ReturnToPreviousScreen = "return_to_previous_screen",
  ShowVideoDescription = "show_video_description",
  HideVideoDescription = "hide_video_description",
  Share = "share",
  CopyShareLink = "copy_share_link",
  Login = "login",
  TwoFAScreen = "2fa_screen",
  Reauthenticate = "reauthenticate",
  Logout = "logout",
  ChangeBackendServer = "change_backend_server",
  PullToRefresh = "pull_to_refresh",
  TabFocus = "tab_focus",
  TabBlur = "tab_blur",
  AppInBackground = "app_in_background",
  AppInForeground = "app_in_foreground",
  VideoCompleted = "video_completed",
  BandwidthChanged = "bandwidth_changed",
  PlaybackQualityDegradation = "playback_quality_degradation",
  SessionExpired = "session_expired",
  PlaybackSpeedChanged = "playback_speed_changed",
  InstanceSearchTextChanged = "instance_search_text_changed",
  VideoView = "video_view",
  VideoPercentageComplete = "video_percentage_complete",
  VideoPlayback = "video_playback",
}

export const DebugLevelCustomPostHogEvents = [CustomPostHogEvents.MuteAudio, CustomPostHogEvents.UnmuteAudio];

export enum CustomPostHogExceptions {
  OutOfMemory = "out_of_memory",
  VideoPlayerError = "video_player_error",
  HttpRequestError = "http_request_error",
  ChromecastError = "chromecast_error",
  TokenError = "token_error",
  RateLimitError = "rate_limit_error",
}
