name: Build Android TV .APK

on:
  workflow_call:
    inputs:
      owntube_source:
        required: false
        type: string
        description: "The repository with OwnTube-tv/web-client code. Defaults to the source repository."
      use_parent_repo_customizations:
        required: false
        type: boolean
        description: "Should a parent repo be used for customizations? (Required for branded builds)"
      customizations_env_content:
        required: false
        type: string
      build_info:
        required: true
        type: string

jobs:
  build_android_tv_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.owntube_source || github.repository }}

      - name: Checkout parent repo with customizations
        uses: actions/checkout@v4
        if: ${{ inputs.use_parent_repo_customizations }}
        with:
          path: customizations

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: cd OwnTube.tv/ && npm install

      - name: Create .env File
        if: ${{ inputs.customizations_env_content != '' }}
        run: |
          echo "${{ inputs.customizations_env_content }}" > ./OwnTube.tv/.env

      - name: Expo Prebuild Android TV Assets
        env:
          EXPO_PUBLIC_ANDROID_RELEASE_SIGNING_STORE_FILE_NAME: "debug.keystore"
          EXPO_PUBLIC_ANDROID_RELEASE_SIGNING_STORE_FILE_PASSWORD: "android"
          EXPO_PUBLIC_ANDROID_RELEASE_SIGNING_KEY_ALIAS: "androiddebugkey"
          EXPO_PUBLIC_ANDROID_RELEASE_SIGNING_KEY_PASSWORD: "android"
        run: export EXPO_TV=1 && cd OwnTube.tv/ && npx expo prebuild --clean --platform android

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Change Wrapper Permissions
        run: cd OwnTube.tv/android/ && chmod +x ./gradlew

      - name: Inject Build Info
        run: |
          cat > ./OwnTube.tv/build-info.json << 'EOF'
          ${{ inputs.build_info }}
          EOF

      - name: Build Release APK by @${{ github.actor }}
        run: export EXPO_TV=1 && cd OwnTube.tv/android/ && ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release TV apk
          path: "./OwnTube.tv/android/app/build/outputs/apk/release/app-release.apk"
